### ISSUE TITLE
Token Factory Release Tracking Issue

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/tokenfactory#1]
This tracking issue aims to outline  the various steps involved in the release process for the Token Factory, as we transition it into a standalone repository.

A key objective in isolating Token Factory into its own repository is to enhance its compatibility across multiple blockchain chains that utilize different versions of the SDK. Starting with releasing a version that uses sdk 0.46, we intend to roll out updates aligned with each subsequent minor version of the Cosmos SDK, up to version 0.50.

Planned releases and subsequent tasks for each release are as follows:
- v0.45
  - [x] Bring types package, keeper package, client package, module.go 
  - [x] Create working simapp and confirm working sim app & sim test
  - [x] Mitigate existing tests using simapp
  - [x] Make proper Makefile for repo
     - handle build
     - handle tests
  - [ ] add test cases 
  - [ ] Manual QAing and add seeds
- v0.46
   - [ ] store key types API change
 - v0.47
   - [ ] bump sdk version to v0.47
   - [ ] Authz is introduced in sdk v0.47, add support for authz in codec
 - v0.50 
    - [ ] Bump sdk version to v0.50
    - [ ] Add Bank Hooks using injectible restrictions on bank module (introduced in sdk v0.50): Known as BlockBeforeSend and TrackBeforeSend: more details in README.md
